[project]
name = "trustmark"
version = "0.1.0-dev"
description = "Proof of Concept Trustmark Service is a service that provides trustmarks for repositories based on the FAIR principles. It evaluates repositories against a set of criteria and generates trustmarks that indicate the level of compliance with the FAIR principles. The service is designed to help researchers and data managers identify trustworthy repositories for their data and to encourage repositories to improve their practices to meet the FAIR principles."
readme = "README.md"
authors = [
    {name = "Amal Khairunnisa", email = "amal.indarto@gmail.com"},
    {name = "Ivan Sandor", email = "ivansndr@pawz.hu"},
    {name = "Margarita Fedulova", email = "m.fedulova@student.fontys.nl"},
]
requires-python = ">=3.12.8"
dependencies = [
    "dynaconf>=3.2.12",
    "fastapi>=0.135.1",
    "feedparser>=6.0.12",
    "jinja2>=3.1.6",
    "locust>=2.43.3",
    "pydantic>=2.12.5",
    "psycopg2-binary>=2.9.10",
    "pytest>=9.0.2",
    "sqlalchemy-orm>=1.2.10",
    "python-multipart>=0.0.22",
    "sqlalchemy>=2.0.48",
    "tomli>=2.4.0",
    "uvicorn>=0.41.0",
    "emoji>=2.15.0",
    "python-jose[cryptography]>=3.5.0",
    "requests>=2.33.1",
    "ruff>=0.15.12",
    "web3>=7.16.0",
]

[project.scripts]
start = "trustmark.main:main"

[tool.uv]
package = true

[tool.trustmark]
title = "Proof of Concept Trustmark Service"

