name: trustmark

services:
  postgres:
    image: postgres:16-alpine
    container_name: trustmark-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-trustmark}
      POSTGRES_USER: ${POSTGRES_USER:-trustmark}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-trustmark}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - ../resources/data/db/pg-db:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-trustmark} -d ${POSTGRES_DB:-trustmark}",
        ]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    volumes:
      - ./realms/realm-export.json:/opt/keycloak/data/import/realm-export.json:ro
    command:
      - start-dev
      - --import-realm
    environment:
      - DB_VENDOR=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/${POSTGRES_DB:-trustmark}
      - KC_DB=postgres
      - KC_DB_USERNAME=${POSTGRES_USER:-trustmark}
      - KC_DB_PASSWORD=${POSTGRES_PASSWORD:-trustmark}
      - KC_BOOTSTRAP_ADMIN_USERNAME=${KEYCLOAK_USER}
      - KC_BOOTSTRAP_ADMIN_PASSWORD=${KEYCLOAK_PASS}
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
  app:
    build:
      context: /home/runner/work/V2-Backend/V2-Backend
      dockerfile: .github/docker/Dockerfile
      args:
        BUILD_DATE: ${BUILD_DATE:-unknown}
    container_name: trustmark-app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      BASE_DIR: /home/runner/work/V2-Backend/V2-Backend/
      EXPOSE_PORT: 41012
      KEYCLOAK_ISSUER: ${KEYCLOAK_ISSUER:-http://keycloak:8080/realms/nextjs-kc}
      CORS_ALLOW_ORIGINS: ${CORS_ALLOW_ORIGINS:-http://localhost:3000}
      DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER:-trustmark}:${POSTGRES_PASSWORD:-trustmark}@postgres:5432/${POSTGRES_DB:-trustmark}
      TEST_MODE: ${TEST_MODE:-False}
    ports:
      - "${EXPOSE_PORT:-41012}:41012"
    volumes:
      - ../../conf:/home/runner/work/V2-Backend/V2-Backend/conf
      - ../../logs:/home/runner/work/V2-Backend/V2-Backend/logs
      - ../../resources/data/files-storage:/home/runner/work/V2-Backend/V2-Backend/resources/data/files-storage
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:41012/api/v1/health"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 20s
    restart: unless-stopped

volumes:
  postgres_data:
